---
abstract: 'a set of historic maps for Games::Risk'
author:
  - 'Jerome Quelin'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Risk-ExtraMaps-History
provides:
  Games::Risk::ExtraMaps::History:
    file: lib/Games/Risk/ExtraMaps/History.pm
    version: 3.112691
  Games::Risk::Map::Roman_empire:
    file: lib/Games/Risk/Map/Roman_empire.pm
    version: 3.112691
requires:
  Games::Risk::ExtraMaps: 0
  Games::Risk::Map: 0
  Locale::Messages: 0
  Locale::TextDomain: 0
  Moose: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Games-Risk-ExtraMaps-History
  homepage: http://search.cpan.org/dist/Games-Risk-ExtraMaps-History/
  repository: git://github.com/jquelin/games-risk-extramaps-history.git
version: 3.112691
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.112400
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@JQUELIN/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@JQUELIN/PruneFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@JQUELIN/AutoPrereqs'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@JQUELIN/MetaJSON'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git::Check'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git::Commit'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@JQUELIN/Git::CommitBuild'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/TagMaster'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/TagRelease'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git::Push'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300002
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300002
